
server:
  port: 8081
spring:
  data:
    mongodb:
      host: ${SPRING_DATA_MONGODB_HOST:127.0.0.1}
      port: ${SPRING_DATA_MONGODB_PORT:27017}
      database: ${SPRING_DATA_MONGODB_DATABASE:phonebook}